#	D I G I T I Z E R 
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 1
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.26
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 459.9 keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 521.1 keV



#	C O I N C I    S O R T E R 
#	C O I N C I    S O R T E R 
/gate/digitizer/Coincidences/setWindow 3. ns
/gate/digitizer/Coincidences/MultiplesPolicy  takeWinnerOfGoods
/gate/digitizer/Coincidences/minSectorDifference 1
#/gate/digitizer/Coincidences/allPulseOpenCoincGate true

/gate/digitizer/name delay
/gate/digitizer/insert coincidenceSorter
#/gate/digitizer/delay/setWindow 120. ns
#/gate/digitizer/delay/setOffset 500. ns
#/gate/digitizer/delay/setWindow 1. ns
#/gate/digitizer/delay/setOffset 500. ns

/gate/digitizer/delay/MultiplesPolicy  takeWinnerOfGoods


