#	D I G I T I Z E R 
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 1
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.26
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 459.9 keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 562.1 keV



#	C O I N C I    S O R T E R 
/gate/digitizer/Coincidences/setWindow 100. ns
/gate/digitizer/Coincidences/minSectorDifference 1
/gate/digitizer/Coincidences/MultiplesPolicy  killAll

# takeAllGoods
# takeWinnerOfGoods
# takeWinnerIfIsGood
# takeWinnerIfAllAreGoods
# keepIfAnyIsGood
# keepIfAllAreGoods
# killAllIfMultipleGoods
# killAll

/gate/digitizer/name delay
/gate/digitizer/insert coincidenceSorter
/gate/digitizer/delay/setWindow 10. ns
#/gate/digitizer/delay/setOffset 500. ns
#/gate/digitizer/delay/MultiplesPolicy  takeWinnerOfGoods
/gate/digitizer/delay/MultiplesPolicy  takeWinnerOfGoods
