
/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType gamma
/gate/source/PBS/setActivity 1000. becquerel
/gate/source/PBS/setEnergy 1.0 MeV
/gate/source/PBS/setSigmaEnergy 0.01 MeV
/gate/source/PBS/setPosition 0 0 0 mm
/gate/source/PBS/setSigmaX 2 mm
/gate/source/PBS/setSigmaY 40 mm
/gate/source/PBS/setSigmaTheta 3.3 mrad
/gate/source/PBS/setSigmaPhi 3.8 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 20 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative
/gate/source/PBS/setRotationAxis 0 1 0
/gate/source/PBS/setRotationAngle -90 deg
